#-------------------------
# 配置文件占位符:
# {date}:2018-04-21
# {short_data}:20180421
# {month}:201804
# {year}:2018
#--------------------------
[common]
#跳过的天数
skip_day=8

#原日志全名称
source_log_file=/data1/adjust/logs/adjust_event_zjdyl_tw/*.{date}.log

#tar,md5文件临时保存路径
tar_md5_file_dir=/data/script/cos_zjdyl_tw/tmp/

#tar,md5文件名 
tar_file_name=ZjdylTWAd_{date}.log.tar.gz
md5_file_name=ZjdylTWAd_{date}.log.tar.gz.md5

#tar文件,md5文件在cos上储存路径 
tar_cos_dir=sincetimeslog2018/zjdyl_tw_ad/{month}/
md5_cos_dir=sincetimeslog2018/zjdyl_tw_ad/md5/

#tar文件,md5文件在cos上储存路径 (2018年前日志存sincetimeslog1中)
#tar_cos_dir= sincetimeslog1/dow/{month}/
#md5_cos_dir= sincetimeslog1/dow/md5/

#coscmd命令路径,解决有时crontab不能读取环境变量问题,/usr/local/bin/
coscmd_path=/usr/local/bin/


[monitor]
#监控文件路径
#md5校验通过,写入文件,文件会一直保存
ftp_monitor_dir=/data/script/save/ftp
#大数据需要使用的路径,使用后会删除文件
ftp_monitor_dir1=/data/script/log/ftp
#cos上传后,写入文件
cos_monitor_dir=/data/script/save/cos
cos_monitor_dir1=/data/script/log/cos
#监控文件名
monitor_file=day_{short_data}_zjdyl_tw_ad
