#-------------------------
# 配置文件占位符:
# {date}:2020-06-19
# {short_data}:20200619
# {month}:202006
# {year}:2020
#--------------------------
[common]
#跳过的天数
skip_day=3

#原日志全名称
source_log_file=/data/stat/Log/LogStat_{date}_*.log

#tar,md5文件临时保存路径
tar_md5_file_dir=/data/logupload/lnzj

#tar,md5文件名 
tar_file_name=LnzjStat_{date}.log.tar.gz
md5_file_name=LnzjStat_{date}.log.tar.gz.md5

#tar文件,md5文件在cos上储存路径 
tar_cos_dir=sincetimeslog2018/blockwar_om/{month}/
md5_cos_dir=sincetimeslog2018/blockwar_om/md5/

#tar文件,md5文件在cos上储存路径 (2018年前日志存sincetimeslog1中)
#tar_cos_dir= sincetimeslog1/dow/{month}/
#md5_cos_dir= sincetimeslog1/dow/md5/

#coscmd命令路径,解决有时crontab不能读取环境变量问题,/usr/local/bin/
coscmd_path=/usr/local/bin/


[monitor]
#监控文件路径
#md5校验通过,写入文件,文件会一直保存
ftp_monitor_dir=/data/script/logupload/save/ftp
#大数据需要使用的路径,使用后会删除文件
ftp_monitor_dir1=/data/script/logupload/log/ftp
#cos上传后,写入文件
cos_monitor_dir=/data/script/logupload/save/cos
cos_monitor_dir1=/data/script/logupload/log/cos
#监控文件名
monitor_file=day_{short_data}_blockwar_om


#目标服务器信息
[destination]
ip=119.28.83.11
username=lnzj
password=lnzj$6668

#目标服务器保存目录
destination_dir=/data1/logupload/lnzj_tw/stat
